### ISSUE TITLE
Prefer bullets under each item not sentences

### ISSUE THREAD

**Issue by time4testing** [ellekasai/resumecards#10]
School and underneath some of the things like degree, honors, awards, extracurricular
Work will bullet items with tools, languages and accomplishments using them would be a better sales tool.
If possible expand the size of the template to be able to contain more information.  Thanks.
Suggest that it be similar to a handbill.  
http://www.career-prospectors.com/pdf/Sample%20Handbills.pdf

**Comment by ellekasai** [comment]
Sorry that the design doesn't work for you. The max length of the text being limited is a design choice.
