### ISSUE TITLE
Template resizing bug at 1200px

### ISSUE THREAD

**Issue by swisspol** [ellekasai/resumecards#3]
Thanks for this great template! I've used it for my personal website which I wanted to redo for a long time, and that's exactly the type of simple and clean design I had been looking for.

In the stylesheet, where you override:

``` css
$container-large-desktop: 970px;
```

It should actually be:

``` css
$container-desktop: 970px;
$container-large-desktop: 970px;
```

Otherwise if you resize the browser window from 1200px wide to 1199px, you will notice the layout on the page slightly changing. This is because `$container-desktop` is 960px by default, a 10px difference.

1200px

![image](https://cloud.githubusercontent.com/assets/627915/7917657/c0244312-0840-11e5-8da7-2fb3bcbc1467.png)

1199px

![image](https://cloud.githubusercontent.com/assets/627915/7917662/c67b8036-0840-11e5-9a65-83a68292c54d.png)

**Comment by ellekasai** [comment]
Thank you for making this issue and so sorry for my late reply! I just fixed it :D!
https://github.com/ellekasai/resumecards/commit/999fc6a355e31e21d68f9116fb06103ce6b84cff
