### ISSUE TITLE
the dropdown of Theme doesn't work

### ISSUE THREAD

**Issue by ddbullfrog** [ellekasai/resumecards#7]
Hi Elle,

env: osx, chrome v49

{code}

<div class="dropdown resume-dropdown">
            <button type="button" class="dropdown-toggle btn btn-default" data-toggle="dropdown" role="button" aria-expanded="false">Theme <span class="caret"></span></button>
            <ul class="dropdown-menu resume-dropdown-menu" role="menu">
              <li><a href="#" id="default">Default</a></li>
              <li><a href="#" id="red">Red</a></li>
              <li><a href="#" id="pink">Pink</a></li>
              <li><a href="#" id="brown">Brown</a></li>
              <li><a href="#" id="blue">Blue</a></li>
              <li><a href="#" id="purple">Purple</a></li>
              <li><a href="#" id="teal">Teal</a></li>
              <li><a href="#" id="green">Green</a></li>
            </ul>
</div>

{code}

Thanks,
Dong

**Comment by ellekasai** [comment]
Sorry I cannot reproduce this. Let me know if anyone else has the same issue.
