### ISSUE TITLE
Way to deploy as subfolder of existing GitHub pages site?

### ISSUE THREAD

**Issue by neontapir** [ellekasai/resumecards#8]
I really like the look of the resume cards. I'd love to deploy this as a subfolder of my main Github Pages website at the root, so that when people visit url.my/resume, they see the resumecards index page.

However, I don't know enough Jekyll fu to make this work. I'm running into include path issues like `Liquid Exception: Included file '_includes/nav.html' not found in resume/index.html`. Is there a directive I can use to keep the server from trying to use the root as my base path for the resumecards content, yet won't affect the functionality of the root site?

Thanks in advance!

**Comment by chibicode** [comment]
For those still looking to figure this out, you can set `baseUrl` in `_config.yml`, and then do:

`{{ page.url | prepend: site.github.url }}`

and then `jekyll build`, then copy paste the generated `_site` directory into the subfolder of your github page directory.
